baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'tl'

theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "🚲"
  description = "Thomas' personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "thomas.lentali@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/tlentali/"
[[params.social]]
  name = "Stack Overflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 2
  url = "https://stackoverflow.com/users/8479387/tlentali"
[[params.social]]
  name = "Kaggle"
  image = "/img/social/kaggle.svg"
  weight = 3
  url = "https://www.kaggle.com/tlentali"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/thomas-lentali/"
[[params.social]]
  name = "Keybase"
  icon = "fa fa-keybase fa-2x"
  weight = 5
  url = "https://keybase.io/tlentali"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 6
  url = "https://gitlab.com/tlentali/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 7
  url = "https://www.instagram.com/th8mm/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 8
  url = "https://twitter.com/tlentali/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"